In [46]:
import torch
import torch.nn as nn

In [47]:
H=56
W=56
C=64
B=4

In [25]:
# x_list=[]
# in_x1 = torch.rand(B,C,H,W)
# in_x2 = torch.rand(B,C,H,W)
# in_x3 = torch.rand(B,C,H,W)
# in_x4 = torch.rand(B,C,H,W)

# x_list.append(in_x1)
# x_list.append(in_x2)
# x_list.append(in_x3)
# x_list.append(in_x4)
# # print(x_list[0].shape)


In [26]:
# class Conv3d_BN_concat(nn.Module):
#     # input: attention list of length #path
#     def __init__(
#         self,
#         in_ch,
#         out_ch,
#         kernel_size=1,
#         stride=1,
#         pad=0,
#         dilation=1,
#         groups=1,
#         bn_weight_init=1,
#         act_layer=None,
#         norm_cfg="BN",
#     ):
#         super().__init__()
    
#         self.bn = nn.BatchNorm2d(out_ch)

#         torch.nn.init.constant_(self.bn.weight, bn_weight_init)
#         torch.nn.init.constant_(self.bn.bias, 0)
#         for m in self.modules():
#             if isinstance(m, nn.Conv2d):
#                 nn.init.xavier_uniform_(m.weight)
#                 if m.bias is not None:
#                     nn.init.zeros_(m.bias)
       
#         self.interact_concat = nn.Sequential(
#             nn.Conv3d(in_ch, out_ch, kernel_size=(4,1,1)),
#             nn.ReLU()
#         )

#     def forward(self, x_list):
        
#         b,c,h,w = x_list[0].shape
#         print(f"b:{b} c:{c} h:{h} w:{w}")
#         out_3d = []
#         for ip in range(len(x_list)):
# #             print(f'ip:{ip}')
#             in_x = x_list[ip]  
# #             print(f'in each {ip} iteration: {in_x.shape}')
#             in_x = in_x.unsqueeze_(dim=2)
#             out_3d.append(in_x)
# #             print(f'{ip} path extend to shape: {in_x.shape}')

#         x = torch.cat(out_3d, dim=2)
# #         print(f'after concat: {x.shape}')
#         x = torch.squeeze(self.interact_concat(x), dim=2)
# #         print(f'after squeeze: {x.shape}')
#         x = self.bn(x)

#         return x



In [27]:
# conv3d_concat = Conv3d_BN_concat(C,2*C)
# x_out = conv3d_concat(x_list)
# print(x_out.shape)

b:4 c:64 h:56 w:56
torch.Size([4, 128, 56, 56])


https://github.com/VITA-Group/ABD-Net

In [48]:
from torch.nn import Module, Conv2d, Parameter, Softmax

class CAM_Module(Module):
    """ Channel attention module"""

    def __init__(self, in_dim):
        super().__init__()
        self.channel_in = in_dim

        self.gamma = Parameter(torch.zeros(1))
        self.softmax = Softmax(dim=-1)
        self.numpath = 3

    def forward(self, x):
        """
            inputs :
                x : input feature maps( B  C  H  W)
            returns :
                out : attention value + input feature
                attention: B X C X C
        """
        m_batchsize, C,numpath, height, width = x.size()
        proj_query = x.view(m_batchsize, C, numpath, -1) #b c 4 n
        print(f'Shape of query: {proj_query.shape}')
        proj_key = x.view(m_batchsize, C,numpath, -1).permute(0, 1, 3, 2) #b c n 4
        print(f'Shape of key: {proj_key.shape}') 
        energy = torch.matmul(proj_query, proj_key) # b c 4 4
        print(f'Shape of energy: {energy.shape}')
        max_energy_0 = torch.max(energy, -1, keepdim=True)[0].expand_as(energy)
        energy_new = max_energy_0 - energy
        attention = self.softmax(energy_new)
        print(f'Shape of attention: {attention.shape}')
        proj_value = x.view(m_batchsize, C, numpath, -1)
        print(f'Shape of proj_value: {proj_value.shape}')

        out = torch.matmul(attention, proj_value)# can be replace by torch.matmul
        out = out.view(m_batchsize, C, numpath, height, width)

#         logging.debug('cam device: {}, {}'.format(out.device, self.gamma.device))
        gamma = self.gamma.to(out.device)
        out = gamma * out + x
        return out



In [49]:
cam = CAM_Module(in_dim = C)

torch.Size([4, 64, 4, 56, 56])
Shape of query: torch.Size([4, 64, 4, 3136])
Shape of key: torch.Size([4, 64, 3136, 4])
Shape of energy: torch.Size([4, 64, 4, 4])
Shape of attention: torch.Size([4, 64, 4, 4])
Shape of proj_value: torch.Size([4, 64, 4, 3136])
torch.Size([4, 64, 4, 56, 56])


In [51]:
class Conv3d_BN_channel_attention_concat(nn.Module):
    # input: attention list of length #path
    def __init__(
        self,
        in_ch,
        out_ch,
        kernel_size=1,
        stride=1,
        pad=0,
        dilation=1,
        groups=1,
        bn_weight_init=1,
        act_layer=None,
        norm_cfg="BN",
    ):
        super().__init__()
    
        self.bn = nn.BatchNorm2d(out_ch)

        torch.nn.init.constant_(self.bn.weight, bn_weight_init)
        torch.nn.init.constant_(self.bn.bias, 0)
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.xavier_uniform_(m.weight)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)
       
        self.interact_concat = nn.Sequential(
            nn.Conv3d(in_ch, out_ch, kernel_size=(4,1,1)),
            nn.ReLU()
        )
        self.channelAttention = CAM_Module(in_dim = in_ch)

    def forward(self, x_list):
        
        b,c,h,w = x_list[0].shape
        print(f"b:{b} c:{c} h:{h} w:{w}")
        out_3d = []
        for ip in range(len(x_list)):
#             print(f'ip:{ip}')
            in_x = x_list[ip]  
#             print(f'in each {ip} iteration: {in_x.shape}')
            in_x = in_x.unsqueeze_(dim=2)
            out_3d.append(in_x)
#             print(f'{ip} path extend to shape: {in_x.shape}')

        x = torch.cat(out_3d, dim=2)
        print(f'before channel attention: {x.shape}')
        x = self.channelAttention(x)
        print(f'after concat: {x.shape}')
        x = torch.squeeze(self.interact_concat(x), dim=2)
        print(f'after squeeze: {x.shape}')
        x = self.bn(x)

        return x



In [52]:
x_list=[]
in_x1 = torch.rand(B,C,H,W)
in_x2 = torch.rand(B,C,H,W)
in_x3 = torch.rand(B,C,H,W)
in_x4 = torch.rand(B,C,H,W)

x_list.append(in_x1)
x_list.append(in_x2)
x_list.append(in_x3)
x_list.append(in_x4)

attention_concat = Conv3d_BN_channel_attention_concat(C,2*C)
x_out = attention_concat(x_list)

b:4 c:64 h:56 w:56
before channel attention: torch.Size([4, 64, 4, 56, 56])
Shape of query: torch.Size([4, 64, 4, 3136])
Shape of key: torch.Size([4, 64, 3136, 4])
Shape of energy: torch.Size([4, 64, 4, 4])
Shape of attention: torch.Size([4, 64, 4, 4])
Shape of proj_value: torch.Size([4, 64, 4, 3136])
after concat: torch.Size([4, 64, 4, 56, 56])
after squeeze: torch.Size([4, 128, 56, 56])


In [2]:
from torch.nn import Module, Conv2d, Parameter, Softmax
import torch

In [4]:
in_x = torch.rand(1,4,4)

softmax1 = Softmax(dim=-1)
x1 = softmax1(in_x)
print(x1[0])

softmax2 = Softmax(dim=1)
x2 = softmax2(in_x)
print(x2[0])

softmax3 = Softmax(dim=2)
x3 = softmax3(in_x)
print(x3[0])

softmax4 = Softmax(dim=0)
x4 = softmax4(in_x)
print(x4[0])

tensor([[0.3015, 0.1978, 0.3139, 0.1868],
        [0.2168, 0.2544, 0.2007, 0.3281],
        [0.3078, 0.2537, 0.1793, 0.2592],
        [0.2129, 0.3217, 0.3074, 0.1580]])
tensor([[0.2658, 0.1729, 0.2833, 0.1907],
        [0.1578, 0.1836, 0.1496, 0.2765],
        [0.3231, 0.2641, 0.1928, 0.3151],
        [0.2533, 0.3794, 0.3744, 0.2176]])
tensor([[0.3015, 0.1978, 0.3139, 0.1868],
        [0.2168, 0.2544, 0.2007, 0.3281],
        [0.3078, 0.2537, 0.1793, 0.2592],
        [0.2129, 0.3217, 0.3074, 0.1580]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [12]:
max_x3 = torch.max(x3,-1,keepdim=True)
print(max_x3)
max_x3 = max_x3[0].expand_as(max_x3[0])
print(max_x3)

torch.return_types.max(
values=tensor([[[0.3139],
         [0.3281],
         [0.3078],
         [0.3217]]]),
indices=tensor([[[2],
         [3],
         [0],
         [1]]]))
tensor([[[0.3139],
         [0.3281],
         [0.3078],
         [0.3217]]])


In [16]:
in_x = torch.rand(1,64, 4,4)

softmax1 = Softmax(dim=-1)
x5 = softmax1(in_x)
print(x5[0][3])

tensor([[0.2958, 0.2056, 0.2667, 0.2319],
        [0.2414, 0.2539, 0.2209, 0.2838],
        [0.2664, 0.3006, 0.1785, 0.2545],
        [0.1799, 0.2220, 0.2343, 0.3638]])
